"""Add nullable end_date to Schedule

Revision ID: 246977f7530e
Revises: 692e847f965e
Create Date: 2025-07-07 01:22:21.925736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246977f7530e'
down_revision = '692e847f965e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
